name: in-orbit-server

services:
  postgres:
    image: bitnami/postgresql:14.13.0
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=inorbit